name: Build and Release

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Go
        uses: actions/setup-go@v2
        with:
          go-version: '1.19'

      - name: Build
        run: go build -o my ./main/main.go

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: v1.0.0
          release_name: Release 1.0.0
          draft: false
          prerelease: false

      - name: Get Release ID
        id: get_release_id
        run: echo "::set-output name=release_id::$(echo ${{ steps.create_release.outputs.id }} | tr -d '\r')"

      - name: Upload Release Asset
        uses: actions/upload-release-asset@v1
        with:
          asset_path: ./
          asset_name: my
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          release_id: ${{ env.release_id }}
